name: Sync Docker Hub description

on:
  push:
    branches:
      - main
      - docker
      - routeros-arm64
    paths:
      - DOCKERHUB.md
      - README.md
      - routeros/README.md
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch: {}

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Docker Hub repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: netcore24/mikrotik-2fa-telegram-only
          readme-filepath: DOCKERHUB.md

